import numpy as np
import matplotlib.pyplot as plt
x=np.loadtxt('BTE.omega')
#print(x.shape)
#print(x.size)
y=np.loadtxt('BTE.gruneisen')
#print(y.shape)
#print(y.size)
#plt.scatter(x[:,0],y[:,0])
#plt.grid()
#plt.plot(x[:,0],y[:,0],"o",c="r")
#plt.show()
#plt.plot(x[:,1],y[:,1],"v",c=(0.5,0.9,0.5)) #RGB color cpmbination
#plt.show()
#plt.scatter(x[:,1],y[:,1],x[:,5],y[:,5])
#plt.grid()
#plt.plot(x[:,0],y[:,0],"o",x[:,1],y[:,1],"o",x[:,2],y[:,2],"o",x[:,3],y[:,3],"o",x[:,4],y[:,4],"o",x[:,5],y[:,5],"o",)
#plt.show()
plt.figure(figsize=(6,4))
#plt.grid()
#plt.scatter(x,y)
plt.plot(x,y,"o",ms=6,label=['ZA','TA','LA','ZO','TO','LO'])
plt.xlabel('Frequency (rad/ps)',size=12)
plt.ylabel('Mode Gruneisen parameter ($\gamma_{sq}$)',size=12)
plt.legend(loc=4,fontsize=8)
#plt.show()
plt.savefig('GrunvsFreq-1.png',dpi=500)
#plt.plot(x,y,"*")
#plt.show()
#plt.plot(x,y,"v")
#plt.show()